### ISSUE TITLE
Cassandra sink connector : how to add whole topic JSON as it is into single cassandra table column

### ISSUE THREAD

**Issue by neerajk22** [lensesio/kafka-connect-query-language#39]
I am using Cassandra Sink Connector with Kafka, now i want to insert whole topic JSON as it is into single Cassandra table column instead of creating diff cols. so what should be the connector KCQL expression ?

INSERT INTO connector_json_table SELECT * as message FROM test-nk-29-dec

test-nk-29-dec is topic name
connector_json_table is Cassandra Table name

connector_json_table contains only one single column with "Text type", Now i want to insert complete JSON into this col.

**Comment by andrewstevenson** [comment]
@neerajk22 wrong project. Please open on the stream reactor project.
