### ISSUE TITLE
Cassandra sink connector : Not able to auto generate Cassandra table structure based on Avro schema

### ISSUE THREAD

**Issue by neerajk22** [lensesio/kafka-connect-query-language#40]
I am using cassandra sink connector (by lensesio), not able to find any option to auto generate table structure based on Kafka topic schema (Avro schema), As my avro schema contains 50+ fields so it will be very complex to create cassandra table manually, so finding a auto generated way to create cassandra table structure. please suggest better way for same.

**Comment by andrewstevenson** [comment]
@neerajk22 wrong project, Please reopen on the stream reactor project
